version: '3.9'

services:

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: kubeguardian
      DB_PORT: 5432
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: kubeguardian-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kubeguardian
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  jenkins:
    image: jenkins/jenkins:lts
    container_name: kubeguardian-jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  jenkins_home: