pipeline {
    agent any

    stages {

        stage('Check Docker') {
            steps {
                sh 'docker --version'
            }
        }

        stage('Build Backend') {
            steps {
                sh 'docker build -t kubeguardian-backend ./backend'
            }
        }

        stage('Build Frontend') {
            steps {
                sh 'docker build -t kubeguardian-frontend ./frontend'
            }
        }

    }
}